"""Add assigned_to_id to tickets

Revision ID: 4b6481b68fa4
Revises: '001_initial_migration'
Create Date: 2026-08-04 00:39:13.515531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b6481b68fa4'
down_revision: Union[str, None] = '001_initial_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('conversations_ticket_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'tickets', ['ticket_id'], ['id'])
    op.drop_constraint(op.f('feedbacks_message_id_fkey'), 'feedbacks', type_='foreignkey')
    op.create_foreign_key(None, 'feedbacks', 'messages', ['message_id'], ['id'])
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.add_column('tickets', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('tickets_user_id_fkey'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'users', ['assigned_to_id'], ['id'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_user_id_fkey'), 'tickets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tickets', 'assigned_to_id')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.create_foreign_key(op.f('feedbacks_message_id_fkey'), 'feedbacks', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_ticket_id_fkey'), 'conversations', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
